#+title: My personal emacs configuration.
#+PROPERTY: header-args:emacs-lisp :tangle ./config.el

* Theme
We use the package circadian to change between a light and dark theme.
#+begin_src emacs-lisp :tangle yes
(use-package circadian
  :ensure t
  :config
  (setq circadian-themes '(("6:00" . doom-one-light)
                           ("15:00" . doom-palenight)))
  (circadian-setup))
#+end_src
* UI
** Line numbers
#+begin_src emacs-lisp :tangle yes
;; Linenumber
(column-number-mode)
(global-display-line-numbers-mode t)
(setq display-line-numbers-type 'relative) ;; This sets relative line numbers.
#+end_src
** No titlebar
#+begin_src emacs-lisp :tangle yes
;; No titlebar
(add-to-list 'default-frame-alist '(undecorated-round . t))
#+end_src
** Transparency
#+begin_src emacs-lisp :tangle yes
(doom/set-frame-opacity 90) ;; Sets the transparency to 90% at start of doom.
;; (setq doom/set-frame-opacity 90)
#+end_src
** Icons
#+begin_src emacs-lisp :tangle yes
(use-package nerd-icons
  :ensure t)
#+end_src
* Org mode
** General things
#+begin_src emacs-lisp :tangle yes
(use-package org
        :config
        (setq org-ellipsis " ▾") ;; symbol if header is closed
        (setq org-agenda-start-with-log-mode t)
        (setq org-log-done 'time)
        (setq org-log-into-drawer t)
        (setq org-directory "~/Org/") ;; last / was necessary
        (setq org-agenda-files '("todos.org"))
        (setq org-agenda-hide-tags-regexp ".*")
)

(with-eval-after-load 'org (global-org-modern-mode))

(defun mp/org-agenda-open-hook ()
  "Hook to be run when org-agenda is opened"
  (olivetti-mode))

(add-hook 'org-agenda-mode-hook 'mp/org-agenda-open-hook)

(setq org-agenda-prefix-format '(
  (agenda . " %?-2i %t ")
  (todo . " %i %-12:c")
  (tags . " %i %-12:c")
  (search . " %i %-12:c")))

(setq org-agenda-category-icon-alist
      '(("work" (nerd-icons-faicon "" :height 0.8 :v-adjust 0) nil nil :ascent center)
        ("teaching" (nerd-icons-faicon "" :height 0.8 :v-adjust 0) nil nil :ascent center)
        ("home" (nerd-icons-mdicon "󰏚󰠧" :height 0.8 :v-adjust 0) nil nil :ascent center)
        ("privat" (nerd-icons-mdicon "󰏚" :height 0.8 :v-adjust 0) nil nil :ascent center)
        ))
#+end_src
** Org Super Agenda
#+begin_src emacs-lisp :tangle yes
(require 'org-super-agenda)

(setq org-super-agenda-groups
      '(
        (:name "! Overdue "
               :scheduled past
               :order 2
               :face 'error)
        (:name " Today "
               :time-grid t
               :date today
               :scheduled today
               :order 1
               :face 'warning)
        (:name "Teaching "
               :and(:category "teaching")
               :order 3)
        (:name "Haus "
               :and(:category "home")
               :order 3)
        (:name "Privat "
               :and(:category "private")
               :order 3)
        ))

(org-super-agenda-mode t)

(map! :desc "Next Line"
      :map org-super-agenda-header-map
      "j" 'org-agenda-next-line)

(map! :desc "Next Line"
      :map org-super-agenda-header-map
      "k" 'org-agenda-previous-line)
#+end_src

  ;; (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'doom/org-babel-tangle-config)))

(defun mp/tangle-on-save-org-mode-file()
  (when (string= (message "%s" major-mode) "org-mode")
    (org-babel-tangle)))

(add-hook 'after-save-hook 'mp/tangle-on-save-org-mode-file)
#+end_src
** Nice Bullets
[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.  Another option for this is [[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] which we may cover in a later video.
#+begin_src emacs-lisp :tangle yes

  ;; (use-package org-bullets
  ;;   :hook (org-mode . org-bullets-mode)
  ;;   :custom
  ;;   (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src
** Org Roam
We want to use this package as our note taking system.
*** Directory
Org roam directory will be located in the Zettelkasten directory.
#+begin_src emacs-lisp :tangle yes
(setq org-roam-directory "~/Zettelkasten")
#+end_src
*** UI
#+begin_src emacs-lisp :tangle yes
(use-package! org-roam-ui
  :after org-roam
  )
#+end_src
*** The concept
We have two different kinds of notes. *Fleeting notes* and *permanent notes*.
** Org Journal
This sets the path to the directory where to journal notes are located.
#+begin_src emacs-lisp :tangle yes
(setq org-journal-dir "~/Tagebuch")
#+end_src
** Center Buffers
This centers org mode buffers. Looks nicer if the org buffer takes up the whole screen.
#+begin_src emacs-lisp :tangle yes

  (defun mp/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . mp/org-mode-visual-fill))

#+end_src
